### ISSUE TITLE
启动直接崩溃

### ISSUE THREAD

**Issue by luotao-net** [SEA-group/RAA#12]
我的windows是英文版，启动3.1.3.5直接弹框说Raa has stopped working，close the program 或debug the program

**Comment by luotao-net** [comment]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	raa.exe
  Problem Signature 02:	3.1.3.5
  Problem Signature 03:	593d0d01
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.17929
  Problem Signature 06:	4ffa561c
  Problem Signature 07:	1705
  Problem Signature 08:	25
  Problem Signature 09:	System.MissingMethodException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3081
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by diannaojiang** [comment]
系统版本？

**Comment by luotao-net** [comment]
关掉吧，把framwork从4.5升到4.6就解决了
