### ISSUE TITLE
無法連線

### ISSUE THREAD

**Issue by jryangex** [SEA-group/RAA#13]
啟動程式後
顯示
stat_Error
Error connecting to remote server
在2周前是可正常使用的
同網路環境下的其他電腦使用也是正常的
重新解壓縮也無法連線啟動
是否有方式清除殘留設定?
OS:Win10X64 (1607)
DNS:8.8.8.8

**Comment by diannaojiang** [comment]
您可以把raa目录下的config.ini文件删除并下载最新的版本进行覆盖

**Comment by jryangex** [comment]
已下載最新版並在另一空間解壓縮
問題並沒有得到解決

**Comment by diannaojiang** [comment]
https://sea.moe.sh/update-sea/RAA/log.txt
请问您能否访问以下网址

**Comment by jryangex** [comment]
可以

**Comment by diannaojiang** [comment]
建议检查下电脑的防火墙设置。我也再想想有什么会导致无法访问的情况

**Comment by jryangex** [comment]
防火牆關閉也無法訪問
不知道這有沒有幫助
[Report.txt](https://github.com/SEA-group/RAA/files/1083058/Report.txt)

**Comment by jryangex** [comment]
![image](https://user-images.githubusercontent.com/15880794/27260542-56e1be9c-5461-11e7-9e15-10b0f5173838.png)

**Comment by diannaojiang** [comment]
运行命令行 输入ipconfig /flushdns清除一下dns缓存试一下呢？

**Comment by jryangex** [comment]
![image](https://user-images.githubusercontent.com/15880794/27260548-90ec756e-5461-11e7-9ae9-1bbd00ec3dc5.png)
無法

**Comment by Lee02** [comment]
删除RAA目录中的config.ini文件.然后启动RAA.如果弹出错误.点确定
然后再看RAA目录中是否有config.ini文件.
判断:如果没有.则网络错误.和RAA程序无关.
如果生成了config.ini文件.请贴出当前的ini文件内容.

RAA启动判定逻辑:
先判定网络.
连接主服务器.获取主服务器数据.
检测配置文件.也就是config.ini
最后检测语言文件包.

检测顺序是依次进行.只要有一个地方出错.就会弹出这个错误警告.
多半是网络判定导致.

**Comment by jryangex** [comment]
並未生成config.ini文件
試問何種網路環境會無法正常連線?

**Comment by Lee02** [comment]
@jryangex 那可以明确判定为.是网络问题.首先是判定主服务器域名.方式采用socket 端口是80 域名:sea.moe.sh

**Comment by jryangex** [comment]
我ping 的時候使用的是ipv6
這有影響到?

**Comment by jryangex** [comment]
![image](https://user-images.githubusercontent.com/15880794/27261316-494b3fa8-5473-11e7-8a84-6d06ab391b61.png)
![image](https://user-images.githubusercontent.com/15880794/27261320-5394c128-5473-11e7-898a-2550da49b33e.png)
跳轉成asia.b9.aicdn.com是正常的嗎?

**Comment by diannaojiang** [comment]
ping和访问是不同的  我们域名后面是cdn所以你ping到的是cdn 访问理应是不受影响的

**Comment by diannaojiang** [comment]
建议回顾下最近一段时间有没有对电脑进行过什么配置。或是网络是否出现过异常

**Comment by jryangex** [comment]
我把ipv6關閉就正常了@@
雖然原因我也不知道
謝謝各位的幫忙
我很喜歡這個project
