### ISSUE TITLE
【bug汇报】游戏切换出去后依旧显示玩家信息

### ISSUE THREAD

**Issue by WAAutoMaton** [SEA-group/RAA#14]
导致不管做什么都会被玩家信息盖在上面。
虽然好像并没有什么关系还是可以用快捷键关掉.......
版本：不知道版本号写在哪...
系统：Windows 10 x64

**Comment by diannaojiang** [comment]
就是这样的机制，你可以使用快捷键隐藏。早设置里设置快捷键
