### ISSUE TITLE
你好，我想请问下链接不上是需要做什么设置

### ISSUE THREAD

**Issue by vessjessy** [SEA-group/RAA#15]
下下来的3.2.0.0版，第一次运行，提示connection error，不要使用IPV6和GFW，这应该怎么破，谢谢

**Comment by diannaojiang** [comment]
非常抱歉。当前正在维护期。导致用户无法使用。维护完成后将会通知你。
具体公告如下：
SEA group的一些小通告

因相关政策紧缩。本工作组相关服务器即日起进入备案阶段。备案期间服务器无法访问。望广大粉丝用户耐心等待。在此献上最诚挚的道歉。

在此期间。本工作组不会停止内容的更新。相关资讯和新闻将全部以图文方式在本工作组官方微博放出，欢迎关注：http://weibo.com/6026980336/profile
