### ISSUE TITLE
請問ALT+Q的全屏幕可以容許調位置嗎

### ISSUE THREAD

**Issue by chibimonxd** [SEA-group/RAA#7]
請問ALT+Q的全屏幕可以容許調位置嗎
擋到瞄準器..
我的屏幕大小是1920x1080
麻煩大佬了

**Comment by Lee02** [comment]
尊敬的玩家您好!由于RAA屏显提供的是数据显示信息.如果屏显挡住准心可以用ALT+Q关闭掉.

屏显功能不推荐长期开启.因为这样会导致游戏界面杂乱.如果长期开启,这样就必须会习惯界面杂乱情况.

在经过多次测试后.屏显内容是根据wows窗体在显示器上坐标自动获取并且显示的.每次显示都会重新获取.达到实时更新屏显内容.

如果要做到实时跟随.且屏显可以调整大小.这样我们觉得在单一的一个屏显功能上没有必要这么麻烦.毕竟他只是一个信息显示区域.

如果屏显内容可允许操作.那么这样会导致游戏和屏显之间干扰.
-------------------------------------------------------------------------------------------------------------------
目前您的建议我可以给一个我的想法.就是调整整体屏显在屏幕位置.这个功能我们不能采用快捷键.初步构想是采用设置防止.因为这个设置的是相对坐标.只是一个变量.

默认位置变量默认值为1920X1080.开发者测试的位置.如果觉得位置不可是.我们将在后续版本进行增加.让用户自行DIY

最后.感谢你的建议.祝您游戏愉快!

**Comment by chibimonxd** [comment]
完美解決, 謝大佬!
